### ISSUE TITLE
Changing colour scheme

### ISSUE THREAD

**Issue by sje30** [tummychow/lanyon-hugo#13]
If I want to change the colour scheme, as per Lanyon, I thought I could edit 
`themes/lanyon-hugo/layouts/partials/default_head.html` to include:

      <body class="theme=base-0b">

but I can't seem to get this working.  Am I missing something?

e.g. if you view-source at http://sje30.github.io/ I see the body statement has the class line, but the colours have not changed.

**Comment by tummychow** [comment]
typo: you have an equals sign in there, it should be a hyphen. Try that and let me know if it works.

**Comment by tummychow** [comment]
By the way, it looks like you haven't set the [title/tagline](https://github.com/tummychow/lanyon-hugo/blob/master/config.json#L18) config parameters, which causes the masthead divider line to be unusually high. You see that horizontal line at the top of the page, how it's cutting through the sidebar icon? That's a visual bug that results from those parameters being empty. Just in case you were wondering why that's happening.

**Comment by sje30** [comment]
Thank you for both noting my typo (sorry!) and the hint about the title/tagline.  I did have the title/tagline in the config file, but not in the Params section as your example showed me.  I have now fixed both problems.

Would you consider a tiny patch to default_head.html that included a comment to note how to change the colour?  I found this: https://github.com/poole/lanyon#themes but nothing locally in your repo to note how to set the theme.

**Comment by tummychow** [comment]
I would prefer not to duplicate upstream documentation for fear that it gets out of sync, but you're right that it's not obvious. I'll add a link to the readme to make it more discoverable.

**Comment by sje30** [comment]
thanks!  & thanks for taking the time to develop this theme, I am enjoying working with it.
