### ISSUE TITLE
Tags and Categories pages are not generated

### ISSUE THREAD

**Issue by bhavin192** [tummychow/lanyon-hugo#21]
HTML pages are not generated for any taxonomy for example for tags and categories as well as no pages are generated if I have my posts under `/blog/` instead of `/post/` 
Solution would be to have a `list.html` in `layouts/_default/` so that it will be picked up to generate pages for these sections. If we do so, we can remove the `layouts/post/post.html` and `layouts/_default/li.html`

You can see `layouts/_default/list.html` is used by these three types,
http://gohugo.io/templates/lookup-order/#examples-layout-lookup-for-section-pages
http://gohugo.io/templates/lookup-order/#examples-layout-lookup-for-taxonomy-list-pages
http://gohugo.io/templates/lookup-order/#examples-layout-lookup-for-taxonomy-terms-pages

I would like to send patch for this :)

**Comment by tummychow** [comment]
If you already have a patch, then please submit a PR and I'll take a look. Otherwise I'll dig into this sometime in the (indeterminate but hopefully near) future.
