### ISSUE TITLE
Hugo v0.57.1 - No blog posts shown in index.html

### ISSUE THREAD

**Issue by major** [tummychow/lanyon-hugo#28]
I recently upgraded to Hugo v0.57.1 and noticed that my `index.html` had no posts! There's just a "Posts" heading at the top without any posts listed.

I made this change and all the posts appear on the index page again:

```diff
-{{ $paginator := .Paginate (where .Data.Pages "Type" "in" "post") }}
+{{ $paginator := .Paginate (where .Site.Pages "Type" "in" "post") }}
```

That may not be the right long term fix, but I figured it was good to ask about it here.

**Comment by tummychow** [comment]
yep, i think this is what they notified me (and many other theme authors) about today: https://github.com/gohugoio/hugoThemes/issues/682

i'll take a stab at fixing it tomorrow

**Comment by major** [comment]
Thank you @tummychow! That workaround is working for me just fine for now.
