### ISSUE TITLE
No posts on the home page with Hugo version 0.68.3 

### ISSUE THREAD

**Issue by treese** [tummychow/lanyon-hugo#32]
I tried to build my site with Hugo version 0.68.3 and HEAD of Lanyon-Hugo (as of today). The site builds with the fixed pages on the home page, and no posts.

I rolled Hugo back to 0.62 and it seems to build OK, so I'd guess something changed in the Hugo code that affects this in the theme.

**Comment by tummychow** [comment]
can't repro this with the example site. is the source for your site somewhere i can look up, or do you have a minimal reproducer if you can't share your site source?

**Comment by treese** [comment]
Thanks for the quick response. Turns out I had missed the configuration need for mainSections, and using it properly fixed things. Sorry for the false alarm!
