### ISSUE TITLE
adding additional sections in posts

### ISSUE THREAD

**Issue by wyonghao** [tummychow/lanyon-hugo#4]
Hello, I am trying to adding different sections such as you might have two blogs folder each contains a different list of posts. For example I will have section called "otherposts". Here is what I did to achieve that:
1.    In the "content" folder, create  `otherposts` folder
2.    the following are in the theme folder (lanyon-hugo theme folder). Add this entry to the siderbar.html
        `<a class="sidebar-nav-item {{ if eq .Url "otherposts" }} active {{ end }}" href="/otherposts">Other Posts</a>`
3.   In the "indexes" folder create "otherposts.html" as the copy of post.html
4.   create `otherposts` folder with copying the contents from post folder (li.html, single.html) inside `layouts` folder. 

It seems worked, however, this approach seem to be repetitive. any suggestion with better method?
Many thanks!

**Comment by tummychow** [comment]
Sorry, I don't use Hugo anymore so I have no suggestions. You might be better served by the [forum](http://discuss.gohugo.io/).
